name: Build Kernel
on:
  workflow_dispatch:
    inputs:
      REPO:
        description: 'Kernel repository'
        default: 'https://github.com/rsuntk/android_kernel_samsung_a12s'
        required: true
      BRANCH:
        description: 'Kernel branch'
        default: 'android-4.19-stable'
        required: true
      DEVICE_TARGET:
        description: 'Target device to build'
        default: 'a12snsxx'
        type: choice
        options:
          - a12snsxx
          - a21snsxx
          - m12nsxx
      KSU:
        description: 'Add KernelSU support'
        type: boolean
        default: false
      KSU_BRANCH:
        description: 'KernelSU branch'
        required: true
        default: 'main'
      UPDATE_TOOLCHAIN:
        description: 'Update toolchain cache'
        type: boolean
        default: false
      KCFLAGS_W:
        description: 'Enable KCFLAGS=-w'
        type: boolean
        default: false
      BUILD_STOCK:
        description: 'Build for stock ROM'
        type: boolean
        default: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Set Timezone
      run: sudo ln -sf /usr/share/zoneinfo/Asia/Jakarta /etc/localtime

    - uses: actions/checkout@v5
      with:
        fetch-depth: 1

    - name: Clone kernel source
      if: github.event.inputs.UPDATE_TOOLCHAIN != 'true'
      run: git clone --depth=1 --single-branch -b ${{ github.event.inputs.BRANCH }} ${{ github.event.inputs.REPO }} kernel_root

    - name: Cache Toolchain
      id: cache-toolchain
      uses: actions/cache@v5
      with:
        path: ~/neutron-clang
        key: neutron-clang-23

    - name: Prepare Dependencies
      run: chmod +x ./build.sh && bash ./build.sh --setup-deps

    - name: Setup Build Environment
      if: github.event.inputs.UPDATE_TOOLCHAIN != 'true'
      id: buildKernel
      run: |
        cd kernel_root
        gitsha1=$(git rev-parse --short HEAD)
        CODENAME=$(cat ../codename)

        if [[ "${{ github.event.inputs.BUILD_STOCK }}" = "true" ]]; then
          echo "buildDetails=$CODENAME-${{ github.event.inputs.DEVICE_TARGET }}-$(date +%Y%m%d)_$(echo $gitsha1)-STOCK-NIGHTLY" >> $GITHUB_OUTPUT
        else
          echo "buildDetails=$CODENAME-${{ github.event.inputs.DEVICE_TARGET }}-$(date +%Y%m%d)_$(echo $gitsha1)-NIGHTLY" >> $GITHUB_OUTPUT
        fi
        echo "currDate=$(date)" >> $GITHUB_OUTPUT

    - name: Fetch Toolchains
      if: ${{ steps.cache-toolchain.outputs.cache-hit != 'true' || github.event.inputs.UPDATE_TOOLCHAIN == 'true' }}
      env:
        UPDATE_TOOLCHAINS: ${{ github.event.inputs.UPDATE_TOOLCHAIN }}
      run: bash ./build.sh --fetch-toolchains

    - name: Build Kernel
      if: github.event.inputs.UPDATE_TOOLCHAIN != 'true'
      env:
        TG_TOKEN: ${{ secrets.BOT_TOKEN }}
        TG_CHAT_ID: ${{ secrets.CHAT_ID }}
        BUILD_STOCK: ${{ github.event.inputs.BUILD_STOCK }}
        DEVICE_TARGET: ${{ github.event.inputs.DEVICE_TARGET }}
        KSU: ${{ github.event.inputs.KSU }}
        CI_ZIPNAME: "${{ steps.buildKernel.outputs.buildDetails }}.zip"
        KCFLAGS_W: "${{ github.event.inputs.KCFLAGS_W }}"
      run: |
        cd kernel_root
        if [ ! -d ~/.ccache ]; then
          mkdir -p ~/.ccache
        fi
        # Handel KSU
        if [[ "$KSU" == "true" ]]; then
          device_defconfig="arch/arm64/configs/${{ inputs.DEVICE_TARGET }}_defconfig"
          curl -LSs "https://raw.githubusercontent.com/rsuntk/KernelSU/main/kernel/setup.sh" | bash -s "${{ inputs.KSU_BRANCH }}"
          
          echo "CONFIG_KSU=y" >> $device_defconfig
          echo "CONFIG_KSU_DEBUG=n" >> $device_defconfig
          echo "CONFIG_KSU_TOOLKIT=n" >> $device_defconfig
          echo "CONFIG_KSU_EXTRAS=n" >> $device_defconfig
          echo "CONFIG_KSU_TAMPER_SYSCALL_TABLE=y" >> $device_defconfig
          
          # Check if the append was successful
          if ! grep -q "CONFIG_KSU_TAMPER_SYSCALL_TABLE" "$device_defconfig"; then
            echo "Bail! Failed to append defconfig"
            exit 1  # This actually stops the script from continuing
          fi
        fi
        bash ../build.sh

    - name: Upload kernel artifacts
      uses: actions/upload-artifact@v5
      with:
        name: Kernel-${{ steps.buildKernel.outputs.buildDetails }}
        path: |
          kernel_root/out/arch/arm64/boot/Image.gz
          kernel_root/out/.config
