name: Build Kernel
on:
  workflow_dispatch:
    inputs:
      BRANCH:
        description: 'Branch to build'
        default: 'master'
        required: true
      URL:
        description: 'Repository URL'
        default: 'https://github.com/rsuntkOrgs/android_kernel_samsung_a05m-6.6.git'
        required: true
      USE_PRIVATE_REPO:
        description: 'Use private key'
        type: boolean
        default: false
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        path: rootdir
        show-progress: false
        fetch-depth: 1
        
    - name: Prepare dependencies
      run: |
        sudo apt update -y
        sudo apt install rsync bc cpio flex bison aptitude aria2 git python-is-python3 tar perl wget curl lz4 ccache -y
        sudo aptitude install libssl-dev -y

    - name: Clone Kernel Source
      run: |
        if [[ "${{ inputs.USE_PRIVATE_REPO }}" == "true" ]]; then
          ${{ secrets.REPO_CLONE }}
        else
          git clone --depth=1 --single-branch -b ${{ inputs.BRANCH }} ${{ inputs.URL }} kernel_root
        fi
      working-directory: rootdir

    - name: Fetch toolchains
      run: |
        cd kernel_root
        aria2c https://github.com/rsuntkOrgs/android_kernel_samsung_a05m-6.6/releases/download/v1.0/xaa
        aria2c https://github.com/rsuntkOrgs/android_kernel_samsung_a05m-6.6/releases/download/v1.0/xab
        echo "INFO: Appending files and extracting ..."
        cat xaa xab > toolchains.tar.gz; tar -xf toolchains.tar.gz; rm toolchains.tar.gz xaa xab
      working-directory: rootdir

    - name: Prepare timezone fix
      run: |
        sudo rm /etc/localtime
        sudo ln -s /usr/share/zoneinfo/Asia/Jakarta /etc/localtime

    - name: Setup Java
      uses: actions/setup-java@v5
      with:
        distribution: temurin
        java-version: 21

    - name: Build kernel
      id: buildKernel
      run: |
        cd kernel_root
        BUILD_IMG="$(pwd)/out/target/product/a05/obj/KLEAF_OBJ/dist/kernel_device_modules-6.6/mgk_64_k66_kernel_aarch64.user/Image.gz"
        kernelVersion=$(cd kernel-6.6 && make kernelversion && cd ..)
        [ -f $(pwd)/build_kernel.sh ] && bash build_kernel.sh || exit 1
        [ ! -f $BUILD_IMG ] && exit 1
        gitsha1=$(git rev-parse --short HEAD)
        buildDetails="`echo $kernelVersion`-A055F_`echo $gitsha1`-`date +'%Y%m%d%H%M%S'`"
        mv $BUILD_IMG ../rootdir/external/anykernel3; cd ../external/anykernel3; zip -r9 ../AnyKernel3-$(echo $buildDetails).zip *
        echo "buildDetails=$buildDetails" >> $GITHUB_OUTPUT
      working-directory: rootdir

    - name: List trees
      run: |
        cd kernel_root/out/target/product/a05/obj/KLEAF_OBJ/dist/kernel_device_modules-6.6/mgk_64_k66_kernel_aarch64.user/
        ls -la
        find . -type f -name "Image.gz" || echo "Image.gz not found!"
      working-directory: rootdir

    - name: Upload AnyKernel3
      continue-on-error: true
      uses: actions/upload-artifact@v4
      with:
        name: AnyKernel3-${{ steps.buildKernel.outputs.buildDetails }}
        path: rootdir/external/anykernel3/*
        compression-level: 9

    - name: Upload Image.gz
      continue-on-error: true
      uses: actions/upload-artifact@v4
      with:
        name: Image_GZ-${{ steps.buildKernel.outputs.buildDetails }}
        path: rootdir/kernel_root/out/target/product/a05/obj/KLEAF_OBJ/dist/kernel_device_modules-6.6/mgk_64_k66_kernel_aarch64.user/Image.gz
        compression-level: 9

    - name: Upload LKM
      continue-on-error: true
      uses: actions/upload-artifact@v4
      with:
        name: LKM-${{ steps.buildKernel.outputs.buildDetails }}
        path: rootdir/kernel_root/out/target/product/a05/obj/KLEAF_OBJ/dist/kernel_device_modules-6.6/mgk_64_k66_kernel_aarch64.user/drivers/*
        compression-level: 9

      - name: Upload to telegram
        env:
          CHAT_ID: ${{ secrets.CHAT_ID }}
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
          RUN_URL: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}
          TITLE: "Galaxy A05 Kernel"
        run: |
          if [ ! -z "${{ secrets.BOT_TOKEN }}" ]; then
            export VERSION=$(cd kernel_root && git rev-list --count HEAD)
            export MD5SUM="$(md5sum $ZIP | cut -d' ' -f1)"
            ZIP=$(find $(pwd)/external/*.zip)
            pip3 install telethon
            python3 scripts/bot.py $ZIP
          fi
      working-directory: rootdir
